# Generated by Django 5.2.8 on 2025-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Exterior building photo', null=True, upload_to='listings/'),
        ),
    ]
