# Generated by Django 3.2.4 on 2025-11-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20251114_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary exterior building photo', null=True, upload_to='listings/'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Property image (interior, exterior, floor plan, etc.)', upload_to='listings/images/')),
                ('title', models.CharField(blank=True, help_text="Optional title/description of the image (e.g., 'Living Room', 'Master Bedroom')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional longer description of the image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display images in the gallery')),
                ('is_primary', models.BooleanField(default=False, help_text='Use this image as the primary thumbnail for the listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Username or source of the upload', max_length=255)),
                ('listing', models.ForeignKey(help_text='The listing this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_5fba7f_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['is_primary'], name='listings_li_is_prim_17eb21_idx'),
        ),
    ]
