# Generated by Django 5.2.8 on 2025-11-21 00:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20251114_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='coralcity', help_text="External data source key (e.g., 'coralcity')", max_length=50)),
                ('external_id', models.CharField(db_index=True, help_text='Identifier from the external system', max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('deal_type', models.CharField(blank=True, help_text='rent|sale or vendor-specific', max_length=32)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True)),
                ('original_url', models.URLField(blank=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Listing',
                'verbose_name_plural': 'External Listings',
                'indexes': [models.Index(fields=['source', 'external_id'], name='listings_ex_source_97ceb3_idx'), models.Index(fields=['fetched_at'], name='listings_ex_fetched_a86ef6_idx'), models.Index(fields=['updated_at'], name='listings_ex_updated_0da9ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='extlisting_unique_source_external_id')],
            },
        ),
    ]
