# Generated by Django 5.2.8 on 2025-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_externallisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_metro', models.BooleanField(default=True)),
                ('enable_metrobus', models.BooleanField(default=True)),
                ('enable_bus', models.BooleanField(default=False)),
                ('enable_grocery', models.BooleanField(default=True)),
                ('enable_clothing', models.BooleanField(default=True)),
                ('enable_pharmacy', models.BooleanField(default=False)),
                ('radius_metro', models.PositiveIntegerField(default=1500)),
                ('radius_metrobus', models.PositiveIntegerField(default=2000)),
                ('radius_bus', models.PositiveIntegerField(default=600)),
                ('radius_grocery', models.PositiveIntegerField(default=600)),
                ('radius_clothing', models.PositiveIntegerField(default=1200)),
                ('radius_pharmacy', models.PositiveIntegerField(default=600)),
                ('max_metro', models.PositiveIntegerField(default=6)),
                ('max_metrobus', models.PositiveIntegerField(default=6)),
                ('max_bus', models.PositiveIntegerField(default=8)),
                ('max_grocery', models.PositiveIntegerField(default=6)),
                ('max_clothing', models.PositiveIntegerField(default=6)),
                ('max_pharmacy', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Generation Config',
                'verbose_name_plural': 'Map Generation Config',
            },
        ),
    ]
