# Generated by Django 5.2.8 on 2025-11-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_mapgenerationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='enable_minibus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='max_minibus',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='radius_minibus',
            field=models.PositiveIntegerField(default=2500),
        ),
    ]
