# Generated by Django 5.2.8 on 2025-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_mapgenerationconfig_enable_minibus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='enable_bicycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='enable_malls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='enable_parks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='enable_taxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='max_bicycle',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='max_malls',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='max_parks',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='max_taxi',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='radius_bicycle',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='radius_malls',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='radius_parks',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='mapgenerationconfig',
            name='radius_taxi',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
