# Generated by Django 5.2.8 on 2025-11-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_mapgenerationconfig_enable_bicycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallisting',
            name='nearest_distances_m',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
