# Generated by Django 5.2.8 on 2025-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_externallisting_nearest_distances_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyAmenityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_m', models.PositiveIntegerField(default=5000, help_text='Search radius in meters (default: 5km)')),
                ('max_results', models.PositiveIntegerField(default=10, help_text='Maximum results to return per amenity type')),
                ('enable_metro', models.BooleanField(default=True)),
                ('enable_metrobus', models.BooleanField(default=True)),
                ('enable_bus', models.BooleanField(default=True)),
                ('enable_taxi', models.BooleanField(default=True)),
                ('enable_grocery', models.BooleanField(default=True)),
                ('enable_clothing', models.BooleanField(default=True)),
                ('enable_malls', models.BooleanField(default=True)),
                ('enable_parks', models.BooleanField(default=True)),
                ('enable_schools', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nearby Amenity Config',
                'verbose_name_plural': 'Nearby Amenity Config',
            },
        ),
    ]
