# Generated by Django 5.2.8 on 2025-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_nearbyamenityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyamenityconfig',
            name='enable_minibus',
            field=models.BooleanField(default=True),
        ),
    ]
