# Generated by Django 3.2.4 on 2025-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_listings', models.PositiveIntegerField(default=100, help_text='Maximum number of listings to display (default: 100)')),
                ('max_grocery_stores', models.PositiveIntegerField(default=200, help_text='Maximum number of grocery stores to display (default: 200)')),
                ('max_clothing_stores', models.PositiveIntegerField(default=200, help_text='Maximum number of clothing stores to display (default: 200)')),
                ('max_metro_stations', models.PositiveIntegerField(default=100, help_text='Maximum number of metro stations to display (default: 100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Display Configuration',
                'verbose_name_plural': 'Display Configuration',
            },
        ),
    ]
