# Generated by Django 3.2.4 on 2025-11-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_displayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayconfig',
            name='closest_clothing_stores',
            field=models.PositiveIntegerField(default=20, help_text='Number of closest clothing stores to pre-compute per listing (default: 20)'),
        ),
        migrations.AddField(
            model_name='displayconfig',
            name='closest_grocery_stores',
            field=models.PositiveIntegerField(default=20, help_text='Number of closest grocery stores to pre-compute per listing (default: 20)'),
        ),
        migrations.CreateModel(
            name='ClosestStoresCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closest_grocery_ids', models.JSONField(default=list, help_text='List of closest grocery store IDs ordered by distance')),
                ('closest_clothing_ids', models.JSONField(default=list, help_text='List of closest clothing store IDs ordered by distance')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closest_stores_cache', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Closest Stores Cache',
                'verbose_name_plural': 'Closest Stores Cache',
            },
        ),
        migrations.AddIndex(
            model_name='closeststorescache',
            index=models.Index(fields=['listing'], name='listings_cl_listing_5cc6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='closeststorescache',
            index=models.Index(fields=['updated_at'], name='listings_cl_updated_f9c1eb_idx'),
        ),
    ]
